name: Testing

on:
  push:
    branches:
      - master
      - add-e2e-tests
  pull_request:
    branches:
      - master
      - add-e2e-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm ci
      - run: node --run prettier
      - run: node --run test:coverage
      - run: node --run build